# Column sizes
FULL = 20
LEFT = LARGER_COLUMN = 14
RIGHT = SMALLER_COLUMN = 6

# Database strings typically can't be longer than 255.
MAX_STRING_LENGTH = 255
MEDIUM_STRING_LENGTH = 100
SMALL_STRING_LENGTH = 40

MAX_TEXT_LENGTH = 5000
MEDIUM_TEXT_LENGTH = 500
SMALL_TEXT_LENGTH = 300


#首页连续接到题，则加快更新速度
HITS = 5
FASTER_INTERVAL = '4s'
#application.js也有定义
SLOW_INTERVAL = '8s'

#首页今天谁在玩top?
TODAY_USER_TOP_MAX = 50
